version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore Araye.Code.sln
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  project: Araye.Code.sln
deploy:
- provider: NuGet
  api_key:
    secure: sWVLd5IPpLgaaBxGSOPTEmBwD0WRdCDMX8PsgBbj7e1lPBGz+OtA1ex82ocpDjgZ
  skip_symbols: true
